// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupqHFZYM1i-s1c2EvS-ifs_aewGIuMeA',
    appId: '1:25306467440:web:2edc130cb152e52d57b8b5',
    messagingSenderId: '25306467440',
    projectId: 'chipin-c3559',
    authDomain: 'chipin-c3559.firebaseapp.com',
    storageBucket: 'chipin-c3559.appspot.com',
    measurementId: 'G-6KZTBZZXRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zcHb_7LrcnqkBQGHQRWzqz14tRBRMVA',
    appId: '1:25306467440:android:0b6bca2b714b10c057b8b5',
    messagingSenderId: '25306467440',
    projectId: 'chipin-c3559',
    storageBucket: 'chipin-c3559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGP7eLFUHNyJ64Xz1Jk1pdOiZ6Y2A3Grw',
    appId: '1:25306467440:ios:3aefcf816552fd8d57b8b5',
    messagingSenderId: '25306467440',
    projectId: 'chipin-c3559',
    storageBucket: 'chipin-c3559.appspot.com',
    iosClientId: '25306467440-5bhq4sftmavu6qtsu1b9dp31ou7or0gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chipin',
  );
}
